//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication3.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication3.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HomePage_runWeather {
            get {
                return ResourceManager.GetString("HomePage_runWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HomePage_tblCalendar {
            get {
                return ResourceManager.GetString("HomePage_tblCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HomePage_tblEmergency {
            get {
                return ResourceManager.GetString("HomePage_tblEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HomePage_tblPM {
            get {
                return ResourceManager.GetString("HomePage_tblPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HomePage_tblTemperature {
            get {
                return ResourceManager.GetString("HomePage_tblTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HomePage_tblTransportation {
            get {
                return ResourceManager.GetString("HomePage_tblTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_lblMedia {
            get {
                return ResourceManager.GetString("MainWindow_lblMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_lblMicroblog {
            get {
                return ResourceManager.GetString("MainWindow_lblMicroblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu1_1 {
            get {
                return ResourceManager.GetString("MainWindow_menu1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu1_2 {
            get {
                return ResourceManager.GetString("MainWindow_menu1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu1_3 {
            get {
                return ResourceManager.GetString("MainWindow_menu1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu2_1 {
            get {
                return ResourceManager.GetString("MainWindow_menu2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu2_2 {
            get {
                return ResourceManager.GetString("MainWindow_menu2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu2_4 {
            get {
                return ResourceManager.GetString("MainWindow_menu2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu3_1 {
            get {
                return ResourceManager.GetString("MainWindow_menu3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu3_2 {
            get {
                return ResourceManager.GetString("MainWindow_menu3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu4_1 {
            get {
                return ResourceManager.GetString("MainWindow_menu4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu4_2 {
            get {
                return ResourceManager.GetString("MainWindow_menu4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu4_3 {
            get {
                return ResourceManager.GetString("MainWindow_menu4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu5_1 {
            get {
                return ResourceManager.GetString("MainWindow_menu5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu5_2 {
            get {
                return ResourceManager.GetString("MainWindow_menu5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu5_3 {
            get {
                return ResourceManager.GetString("MainWindow_menu5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu6_1 {
            get {
                return ResourceManager.GetString("MainWindow_menu6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu6_2 {
            get {
                return ResourceManager.GetString("MainWindow_menu6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu6_3 {
            get {
                return ResourceManager.GetString("MainWindow_menu6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu6_4 {
            get {
                return ResourceManager.GetString("MainWindow_menu6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu7_1 {
            get {
                return ResourceManager.GetString("MainWindow_menu7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu7_2 {
            get {
                return ResourceManager.GetString("MainWindow_menu7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu7_3 {
            get {
                return ResourceManager.GetString("MainWindow_menu7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu8_1 {
            get {
                return ResourceManager.GetString("MainWindow_menu8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu8_2 {
            get {
                return ResourceManager.GetString("MainWindow_menu8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menu8_3 {
            get {
                return ResourceManager.GetString("MainWindow_menu8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menutitle1 {
            get {
                return ResourceManager.GetString("MainWindow_menutitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menutitle2 {
            get {
                return ResourceManager.GetString("MainWindow_menutitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menutitle3 {
            get {
                return ResourceManager.GetString("MainWindow_menutitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menutitle4 {
            get {
                return ResourceManager.GetString("MainWindow_menutitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menutitle5 {
            get {
                return ResourceManager.GetString("MainWindow_menutitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menutitle6 {
            get {
                return ResourceManager.GetString("MainWindow_menutitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menutitle7 {
            get {
                return ResourceManager.GetString("MainWindow_menutitle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainWindow_menutitle8 {
            get {
                return ResourceManager.GetString("MainWindow_menutitle8", resourceCulture);
            }
        }
    }
}
